keypress("3", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("a", x, bpm)
rest(0.375, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("(", x, bpm)
keypress("a", x, bpm)
rest(0.375, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("3", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.375, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("2", x, bpm)
keypress("a", x, bpm)
rest(0.375, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("9", x, bpm)
keypress("a", x, bpm)
rest(0.375, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("7", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.375, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("1", x, bpm)
keypress("s", x, bpm)
rest(0.375, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("8", x, bpm)
keypress("s", x, bpm)
rest(0.375, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("1", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("a", x, bpm)
rest(0.375, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("(", x, bpm)
keypress("a", x, bpm)
rest(0.375, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("3", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.375, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("2", x, bpm)
keypress("a", x, bpm)
rest(0.375, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("9", x, bpm)
keypress("a", x, bpm)
rest(0.375, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("7", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.375, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("1", x, bpm)
keypress("s", x, bpm)
rest(0.375, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("8", x, bpm)
keypress("s", x, bpm)
rest(0.375, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("1", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
keypress("a", x, bpm)
rest(0.375, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
rest(0.375, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("3", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
keypress("a", x, bpm)
rest(0.875, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("2", x, bpm)
keypress("a", x, bpm)
rest(0.375, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
rest(0.375, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("7", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("s", x, bpm)
rest(0.875, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("1", x, bpm)
keypress("s", x, bpm)
rest(0.375, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
rest(0.375, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("1", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("a", x, bpm)
rest(0.375, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("(", x, bpm)
keypress("a", x, bpm)
rest(0.375, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("3", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.375, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("2", x, bpm)
keypress("a", x, bpm)
rest(0.375, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("9", x, bpm)
keypress("a", x, bpm)
rest(0.375, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("7", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("7"
